# Spring Boot Application Configuration
spring:
  application:
    name: project-management-system
  
  # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/project_management}
      database: ${MONGODB_DATABASE:project_management}
      auto-index-creation: true
      uuid-representation: standard
  
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    time-zone: UTC
  
  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8080/.well-known/jwks.json}
  
  # Cache Configuration
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=600s
    cache-names:
      - users
      - organizations
      - projects
      - tasks
      - documents
  
  # Servlet Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2KB
  
  # Thread Pool Configuration
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
      thread-name-prefix: async-task-
    scheduling:
      pool:
        size: 5
      thread-name-prefix: scheduled-task-

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  servlet:
    context-path: /api
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: ${COOKIE_SECURE:false}
        same-site: strict

# Management and Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}
  health:
    mongo:
      enabled: true
    diskspace:
      enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.projectmanagement: ${LOG_LEVEL:DEBUG}
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO
    org.mongodb.driver: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:logs/application.log}
    max-size: 10MB
    max-history: 30
    total-size-cap: 1GB

# Application Specific Configuration
application:
  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-change-this-in-production}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds
    issuer: ${JWT_ISSUER:project-management-system}
  
  # Security Configuration
  security:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}
    password-encoder-strength: 12
    max-login-attempts: 5
    account-lockout-duration: 30 # minutes
    session-timeout: 30 # minutes
    enable-mfa: ${ENABLE_MFA:false}
  
  # File Storage Configuration
  storage:
    type: ${STORAGE_TYPE:local} # local, s3, azure
    local:
      base-path: ${STORAGE_BASE_PATH:./uploads}
    s3:
      bucket-name: ${S3_BUCKET_NAME:}
      region: ${S3_REGION:us-east-1}
      access-key: ${S3_ACCESS_KEY:}
      secret-key: ${S3_SECRET_KEY:}
    max-file-size: 52428800 # 50MB in bytes
    allowed-extensions: pdf,doc,docx,xls,xlsx,ppt,pptx,txt,jpg,jpeg,png,gif
  
  # Email Configuration
  email:
    enabled: ${EMAIL_ENABLED:false}
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    from: ${EMAIL_FROM:noreply@projectmanagement.com}
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
  
  # Pagination Configuration
  pagination:
    default-page-size: 20
    max-page-size: 100
  
  # Rate Limiting Configuration
  rate-limit:
    enabled: ${RATE_LIMIT_ENABLED:true}
    requests-per-minute: 60
    requests-per-hour: 1000
  
  # Audit Configuration
  audit:
    enabled: true
    retention-days: 90
  
  # Feature Flags
  features:
    enable-document-versioning: ${ENABLE_DOCUMENT_VERSIONING:true}
    enable-task-notifications: ${ENABLE_TASK_NOTIFICATIONS:true}
    enable-project-templates: ${ENABLE_PROJECT_TEMPLATES:true}
    enable-advanced-search: ${ENABLE_ADVANCED_SEARCH:false}
    enable-analytics: ${ENABLE_ANALYTICS:true}
  
  # Integration Configuration
  integration:
    webhook:
      enabled: ${WEBHOOK_ENABLED:false}
      timeout: 5000 # milliseconds
      retry-attempts: 3
    external-api:
      timeout: 10000 # milliseconds
      connection-timeout: 5000 # milliseconds
  
  # Performance Configuration
  performance:
    enable-query-optimization: true
    enable-caching: true
    cache-ttl: 600 # seconds
    async-processing: true
  
  # Monitoring Configuration
  monitoring:
    enable-performance-tracking: true
    enable-error-tracking: true
    slow-query-threshold: 1000 # milliseconds

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}
  allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
  allowed-headers: "*"
  exposed-headers: Authorization,Content-Disposition
  allow-credentials: true
  max-age: 3600